 **occupies less memory
**faster   
**more **convenient**




In [ ]:
import numpy as np
import time
import sys

In [ ]:
r = np.array([2,3,4,5])

In [ ]:
a= np.arange(1000)

In [ ]:
print(r)

[2 3 4 5]


In [ ]:
#print(a)

In [ ]:
# list
l= range(1000)

In [ ]:
print(l)

range(0, 1000)


In [ ]:
# size of list l
print(sys.getsizeof(4)*len(l))
#size of numpy array a
print(a.size*a.itemsize)

28000
4000


In [ ]:
# faster than list
# more convenient [easy  syntax]
l1= range(100)
l2= range(100)
a1 = np.arange(100)
a2 = np.arange(100)
start=time.time()
result_l =[(x,y) for  x,y in zip(l1,l2)]
print((time.time()-start)*100)
start=time.time()
result_a = a1+a2
print((time.time()-start)*100)

0.0
0.08111000061035156


In [ ]:
# find the dimension of array
a= np.array([(1,2),(4,5),(7,8)])
print(a)
print("dimention : ",a.ndim)
# find  byte size of each element
print(a.itemsize)
# total number of elements in array
print( "total num ",a.size)
# find type of the elements
print(a.dtype)

[[1 2]
 [4 5]
 [7 8]]
dimention :  2
4
total num  6
int32


In [ ]:
# shape (number  row & column)
print(a.shape)
#Reshape  means change number of rows and column
r1 = np.array([(3,5),(2,3),(7,6)])
print(r1)
print("shape : ",r1.shape)
r1= r1.reshape(2,3)
print(r1)

(3, 2)
[[3 5]
 [2 3]
 [7 6]]
shape :  (3, 2)
[[3 5 2]
 [3 7 6]]


In [ ]:
#slicing

a= np.array([(1,2),(4,5),(7,8)])
print(a)

print(a[1,0])
print(a[0: :2])

#print(a[row, column])
print(a[0:2,0])
print(a[0:1,1])

#print 1 column elements
print(a[ : ,1])

[[1 2]
 [4 5]
 [7 8]]
4
[[1 2]
 [7 8]]
[1 4]
[2]
[2 5 8]


In [ ]:
# sum
print(a.sum())
#sum of columns
print(a.sum(axis=0))
#sum of rows
print(a.sum(axis=1))

27
[12 15]
[ 3  9 15]


In [ ]:
# find square root of array
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356]
 [2.         2.23606798]
 [2.64575131 2.82842712]]
2.5


In [ ]:
# operations on numpy array

s1 = np.array([(2,4,5),(6,4,7)])
s2 = np.array([(1,4,5),(6,4,2)])
print(s1+s2)
print(s1/s2)

print(s1)
print(s2)
# concatenation of two arrays horizontally and vertically
print(np.vstack((s1,s2)) )

print(np.hstack((s1,s2)))

# convert array into column
print(s1.ravel())

[[ 3  8 10]
 [12  8  9]]
[[2.  1.  1. ]
 [1.  1.  3.5]]
[[2 4 5]
 [6 4 7]]
[[1 4 5]
 [6 4 2]]
[[2 4 5]
 [6 4 7]
 [1 4 5]
 [6 4 2]]
[[2 4 5 1 4 5]
 [6 4 7 6 4 2]]
[2 4 5 6 4 7]


In [24]:
# NumPy Array Copy vs View

#Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#The copy SHOULD NOT be affected by the changes made to the original array.

[42  2  3  4  5]
[1 2 3 4 5]


In [26]:
#Make a view, change the original array, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [27]:
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [2]:
#Searching Arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

y = np.where(arr%2 == 0)

print(x)

(array([3, 5, 6]),)


In [6]:
#   *Splitting NumPy Arrays*
# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [9]:
#  Filtering Arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [10]:
#   ufunc in numpy

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

#without ufunc
for i, j in zip(x, y):
  z.append(i + j)
print(z)


# ufunc
w = np.add(x, y)

print(w)

[5, 7, 9, 11]
[ 5  7  9 11]


In [11]:
# create your own universal function

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [14]:
# Check if a Function is a ufunc

print(type(np.add))

<class 'numpy.ufunc'>


In [15]:
# If it is not a ufunc, it will return another type, like this built-in NumPy function for joining two or more arrays:

print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [17]:
#   Rounding Decimals
# truncation
#fix
#around
#floor
#ceil

#trunc

arr = np.trunc([-3.1666, 3.6667])
print(arr)

# fix

arr = np.fix([-3.1666, 3.6667])
print(arr)

#around

arr = np.around(3.1666, 2)
print(arr)

# floor

arr = np.floor([-3.1666, 3.6667])
print(arr)

#ceil

arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


In [18]:
#Log at Base 2
#Use the log2() function to perform log at the base 2.

In [19]:
arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [20]:
#What is the difference between summation and addition?

#Addition is done between two arguments whereas summation happens over n elements.

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 4, 3])

newarr = np.add(arr1, arr2)

print(newarr)


arr1 = np.array([1, 2, 3])
arr2 = np.array([11, 10, 12])

newarr = np.sum([arr1, arr2])

print(newarr)

arr1 = np.array([1, 22, 3])
arr2 = np.array([11, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[2 6 6]
39
[26 16]


In [23]:
# A discrete difference means subtracting two successive elements.

#E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

#To find the discrete difference, use the diff() function.

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [24]:
#E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] ,
#then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


In [2]:
# The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.
#Find the LCM of the following two numbers:

import numpy as np
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)


#Find the LCM of the values of the following array:
arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)




12
18


In [3]:
#NumPy Trigonometric Functions

In [4]:
# sin
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)


[1.         0.8660254  0.70710678 0.58778525]


In [5]:
#Convert all of the values in following array arr to radians:

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [6]:
#Convert all of the values in following array arr to degrees:


arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [7]:
#NumPy Hyperbolic Functions

In [8]:
#Find sinh value of PI/2:


x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


In [9]:
#Find cosh values for all of the values in arr:

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)


[2.50917848 1.60028686 1.32460909 1.20397209]


In [10]:
# Numpy set operations

In [18]:
#Convert following array with repeated elements to a set:


arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)


[1 2 3 4 5 6 7]


In [16]:
#Find union of the following two set arrays:


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [19]:
#Find intersection of the following two set arrays:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2,)

print(newarr)

[3 4]


In [20]:
#Find the difference of the set1 from set2:


set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)


[1 2]


In [21]:
#Find the symmetric difference of the set1 and set2:
#To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
