In [1]:
#Generate Random Number
#NumPy offers the random module to work with random numbers.

#Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x)

56


In [2]:
#The random module's rand() method returns a random float between 0 and 1.

#Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.7567155334413518


In [3]:
#Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x)

[ 1 25 13 75 63]


In [4]:
#Generate a 1-D array containing 5 random floats:

from numpy import random

x = random.rand(5)

print(x)


[0.65356656 0.01655336 0.47571179 0.72519591 0.85944667]


In [5]:
#The choice() method takes an array as a parameter and randomly returns one of the values.


#Return one of the values in an array:

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)


5


In [6]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 7 3 9 5]
 [9 7 3 7 7]
 [5 5 7 3 9]]


In [9]:
#seed()

"""it can generate same random numbers on multiple executions of the code on the same machine or
on different machines (for a specific seed value). The seed value is the previous value number generated by the generator.
For the first time when there is no previous value, it uses current system time. """

# importing random module
import random

random.seed(3)

# print a random number between 1 and 1000.
print(random.randint(1, 1000))

# if you want to get the same random number again then,
random.seed(3)
print(random.randint(1, 1000))

# If seed function is not used

# Gives totally unpredictable responses.
print(random.randint(1, 1000))


244
244
607


In [10]:
# random module is imported
import random
for i in range(5):

	# Any number can be used in place of '0'.
	random.seed(0)

	# Generated random number will be between 1 to 1000.
	print(random.randint(1, 1000))



865
865
865
865
865


In [12]:
# uniform
#Code to generate float random number.



# for using uniform()
import random

# initializing bounds
a = 8
b = 12


# printing the random number
print("The random number generated between 4 and 9 is : ", end ="")
print(random.uniform(a, b))

The random number generated between 4 and 9 is : 11.560975683348524


In [13]:
#Return a number between 3 and 9:

import random

print(random.randrange(3, 9))


3
